name: CI | Test Handler

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  launch_runner_worker:
    runs-on: ubuntu-latest

  run_tests:
    needs: launch_runner_worker
    runs-on: runpod

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11 & install dependencies
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        env:
          PIP_ROOT_USER_ACTION: "ignore"
        run: |
          python -m pip install --upgrade pip
          pip install -r builder/requirements.txt

      - name: Execute Tests
        run: |
          python src/handler.py --test_input='{"input": {"prompt": "What is RunPod"}}'

